// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCrdCsQJwqv7s5h3wPOwNjmgz39Ivq3pk',
    appId: '1:703934375:web:58eae40879b3f897195082',
    messagingSenderId: '703934375',
    projectId: 'luminej-12257',
    authDomain: 'luminej-12257.firebaseapp.com',
    storageBucket: 'luminej-12257.firebasestorage.app',
    measurementId: 'G-DJJ83XGFYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV4c1mPJr2CFUg6wcDfnoWG9OzdeGDtog',
    appId: '1:703934375:android:94e5d9f7f59daad4195082',
    messagingSenderId: '703934375',
    projectId: 'luminej-12257',
    storageBucket: 'luminej-12257.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMXzOvZ6JuHH6dOoib0L3kDSevoZgtj0E',
    appId: '1:703934375:ios:c92956ad5b33474c195082',
    messagingSenderId: '703934375',
    projectId: 'luminej-12257',
    storageBucket: 'luminej-12257.firebasestorage.app',
    iosBundleId: 'com.example.jewelryShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMXzOvZ6JuHH6dOoib0L3kDSevoZgtj0E',
    appId: '1:703934375:ios:c92956ad5b33474c195082',
    messagingSenderId: '703934375',
    projectId: 'luminej-12257',
    storageBucket: 'luminej-12257.firebasestorage.app',
    iosBundleId: 'com.example.jewelryShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCrdCsQJwqv7s5h3wPOwNjmgz39Ivq3pk',
    appId: '1:703934375:web:148d3bf19bd47e79195082',
    messagingSenderId: '703934375',
    projectId: 'luminej-12257',
    authDomain: 'luminej-12257.firebaseapp.com',
    storageBucket: 'luminej-12257.firebasestorage.app',
    measurementId: 'G-FJEY526CFE',
  );

}